server:
  port: 9001

spring:
  application:
    name: DEPARTMENT-SERVICE
  cloud:
    config:
      enabled: true
      uri: http://localhost:9190
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    enabled: true


